# Generated by Django 5.2 on 2026-04-02 20:04

import django.db.models.deletion
import djmoney.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('STANDARD', 'Стандартный'), ('BEDRIDDEN', 'Лежачий')], max_length=255, null=True, verbose_name='Категория')),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=8, verbose_name='Цена за день')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата изменения')),
                ('name', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('STANDARD', 'Стандартный'), ('BEDRIDDEN', 'Лежачий')], max_length=255, null=True, verbose_name='Категория')),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=8, verbose_name='Цена за день')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('picture', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical комната',
                'verbose_name_plural': 'historical комнаты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата изменения')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Описание')),
                ('phone', models.TextField(max_length=50, verbose_name='Телефон')),
                ('preferred_call_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Удобное время звонка')),
                ('preferred_check_in', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время заселения')),
                ('preferred_budget_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3, null=True)),
                ('preferred_budget', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='RUB', max_digits=8, null=True, verbose_name='Бюджет/сутки')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('PROGRESS', 'В обработке'), ('DONE', 'Обработана')], default='NEW', max_length=30, verbose_name='Статус')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formula.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'historical бронирование',
                'verbose_name_plural': 'historical бронирования',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Описание')),
                ('phone', models.TextField(max_length=50, verbose_name='Телефон')),
                ('preferred_call_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Удобное время звонка')),
                ('preferred_check_in', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время заселения')),
                ('preferred_budget_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3, null=True)),
                ('preferred_budget', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='RUB', max_digits=8, null=True, verbose_name='Бюджет/сутки')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('PROGRESS', 'В обработке'), ('DONE', 'Обработана')], default='NEW', max_length=30, verbose_name='Статус')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formula.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['room', 'status'], name='bookings_room_id_e4aa25_idx')],
            },
        ),
    ]
