# Generated by Django 5.2 on 2026-04-01 07:43

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='modified at')),
                ('name', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('STANDARD', 'Стандартный'), ('BEDRIDDEN', 'Лежачий')], max_length=255, null=True, verbose_name='category')),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=8)),
                ('description', models.TextField(max_length=300)),
                ('picture', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='picture')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical room',
                'verbose_name_plural': 'historical rooms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
