# Generated by Django 5.2 on 2026-04-01 07:44

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_historicalroom_delete_circuit_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroom',
            name='price_per_day_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_day_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3),
        ),
    ]
