# Generated by Django 5.2 on 2026-04-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_alter_historicalroom_price_per_day_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='conditional_field_active',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='conditional_field_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_en',
        ),
    ]
